#!/bin/sh
OUTFILE_PARAMS="/cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/params_all.csv"
OUTFILE_MACRO="/cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/clusters_macro_all.csv"
OUTFILE_MICRO="/cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/clusters_micro_all.csv"
OUTFILE_MACRO_AVG_SPLIT="/cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/clusters_macro_avg_split.csv"
cat /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s0/params.csv > $OUTFILE_PARAMS
cat /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s0/clusters_macro.csv > $OUTFILE_MACRO
cat /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s0/clusters_micro.csv > $OUTFILE_MICRO
cat /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s0/clusters_macro_avg.csv > $OUTFILE_MACRO_AVG_SPLIT
sed -e '1d' /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s1/params.csv >> $OUTFILE_PARAMS
sed -e '1d' /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s1/clusters_macro.csv >> $OUTFILE_MACRO
sed -e '1d' /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s1/clusters_micro.csv >> $OUTFILE_MICRO
sed -e '1d' /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s1/clusters_macro_avg.csv >> $OUTFILE_MACRO_AVG_SPLIT
sed -e '1d' /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s2/params.csv >> $OUTFILE_PARAMS
sed -e '1d' /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s2/clusters_macro.csv >> $OUTFILE_MACRO
sed -e '1d' /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s2/clusters_micro.csv >> $OUTFILE_MICRO
sed -e '1d' /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s2/clusters_macro_avg.csv >> $OUTFILE_MACRO_AVG_SPLIT
sed -e '1d' /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s3/params.csv >> $OUTFILE_PARAMS
sed -e '1d' /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s3/clusters_macro.csv >> $OUTFILE_MACRO
sed -e '1d' /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s3/clusters_micro.csv >> $OUTFILE_MICRO
sed -e '1d' /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s3/clusters_macro_avg.csv >> $OUTFILE_MACRO_AVG_SPLIT
sed -e '1d' /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s4/params.csv >> $OUTFILE_PARAMS
sed -e '1d' /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s4/clusters_macro.csv >> $OUTFILE_MACRO
sed -e '1d' /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s4/clusters_micro.csv >> $OUTFILE_MICRO
sed -e '1d' /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s4/clusters_macro_avg.csv >> $OUTFILE_MACRO_AVG_SPLIT
sed -e '1d' /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s5/params.csv >> $OUTFILE_PARAMS
sed -e '1d' /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s5/clusters_macro.csv >> $OUTFILE_MACRO
sed -e '1d' /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s5/clusters_micro.csv >> $OUTFILE_MICRO
sed -e '1d' /cluster/work/scr3/balistef/NEW/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1/attrLinear_nv_rndseed_rndseq_tm_Rleft_n100_fv1_s5/clusters_macro_avg.csv >> $OUTFILE_MACRO_AVG_SPLIT
