function createAndSaveFigure(cdata1,fileName)
%CREATEFIGURE(CDATA1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 27-Jun-2011 11:40:04

% Create figure
h = figure;

% Create axes
%axes1 = axes('Parent',figure1,'YDir','reverse','Layer','top');
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.5 256.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.5 256.5]);
%box(axes1,'on');
%hold(axes1,'all');

% Create image
A = imagesc(cdata1);%,'Parent',axes1,'CDataMapping','scaled');

%saveas(A,fileName,'jpg');
print(h,'-dpng',fileName);
end