function [ row ] = csv_format_row_clusters_macro( obj , simname, t)
    
    row = sprintf('"%s",%u,%u,%u,%u,%.4f,%.4f,%.4f,%.4f,%.4f,%.4f,%.1f,%.4f,%.4f,%.4f', ... 
        simname, ...
        obj.simnameidx, ...
        obj.run, ... 
        t, ...
        obj.cluster_count(t), ...
        obj.avgcoverage(t), ...
        obj.cumcoverage(t), ...
        obj.mean_cluster_speed(t), ...
        obj.sd_cluster_speed(t), ...
        obj.mean_cluster_move(t), ...
        obj.sd_cluster_move(t), ...
        obj.mean_cluster_size(t), ...
        obj.sd_cluster_size(t), ...
        obj.mean_from_truth(t), ...
        obj.sd_from_truth(t) ...
        );
      
end

