function [ row ] = csv_format_row_clusters_micro(stepData, simname, t, cluster_id)
        
    row = sprintf('"%s",%u,%u,%u,%u,%.4f,%.4f,%.4f', ... 
        simname, ...
        stepData.simnameidx, ...
        stepData.run, ... 
        t, ...
        stepData.clusters_size(cluster_id), ...
        stepData.clusters_speed(cluster_id), ...
        stepData.clusters_move(cluster_id), ...
        stepData.clusters_fromtruth(cluster_id) ...
   );
    
end

