function [ row ] = csv_format_row_clusters_macro( obj , simname, t)
    
    row = sprintf('"%s",%u,%u,%u,%u,%.4f,%.4f,%.4f,%.4f,%.4f,%.4f,%.1f,%.4f,%.4f,%.4f', ... 
        simname, ...
        obj.simnameidx, ...
        obj.run, ... 
        t, ...
        obj.cluster_count, ...
        obj.avgcoverage, ...
        obj.cumcoverage, ...
        obj.mean_cluster_speed, ...
        obj.sd_cluster_speed, ...
        obj.mean_cluster_move, ...
        obj.sd_cluster_move, ...
        obj.mean_cluster_size, ...
        obj.sd_cluster_size, ...
        obj.mean_from_truth, ...
        obj.sd_from_truth ...
        );
      
end

