#!/bin/sh
#OUTFILE_PARAMS="/mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/params_all.csv"
#OUTFILE_MACRO="/mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/clusters_macro_all.csv"
#OUTFILE_MICRO="/mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/clusters_micro_all.csv"
OUTFILE_MACRO_AVG_SPLIT="/mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/clusters_macro_avg_split.csv"
#cat /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s0/params.csv > $OUTFILE_PARAMS
#cat /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s0/clusters_macro.csv > $OUTFILE_MACRO
#cat /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s0/clusters_micro.csv > $OUTFILE_MICRO
cat /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s0/clusters_macro_avg.csv > $OUTFILE_MACRO_AVG_SPLIT
#sed -e '1d' /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s1/params.csv >> $OUTFILE_PARAMS
#sed -e '1d' /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s1/clusters_macro.csv >> $OUTFILE_MACRO
#sed -e '1d' /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s1/clusters_micro.csv >> $OUTFILE_MICRO
sed -e '1d' /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s1/clusters_macro_avg.csv >> $OUTFILE_MACRO_AVG_SPLIT
#sed -e '1d' /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s2/params.csv >> $OUTFILE_PARAMS
#sed -e '1d' /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s2/clusters_macro.csv >> $OUTFILE_MACRO
#sed -e '1d' /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s2/clusters_micro.csv >> $OUTFILE_MICRO
sed -e '1d' /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s2/clusters_macro_avg.csv >> $OUTFILE_MACRO_AVG_SPLIT
#sed -e '1d' /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s3/params.csv >> $OUTFILE_PARAMS
#sed -e '1d' /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s3/clusters_macro.csv >> $OUTFILE_MACRO
#sed -e '1d' /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s3/clusters_micro.csv >> $OUTFILE_MICRO
sed -e '1d' /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s3/clusters_macro_avg.csv >> $OUTFILE_MACRO_AVG_SPLIT
#sed -e '1d' /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s4/params.csv >> $OUTFILE_PARAMS
#sed -e '1d' /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s4/clusters_macro.csv >> $OUTFILE_MACRO
#sed -e '1d' /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s4/clusters_micro.csv >> $OUTFILE_MICRO
sed -e '1d' /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s4/clusters_macro_avg.csv >> $OUTFILE_MACRO_AVG_SPLIT
#sed -e '1d' /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s5/params.csv >> $OUTFILE_PARAMS
#sed -e '1d' /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s5/clusters_macro.csv >> $OUTFILE_MACRO
#sed -e '1d' /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s5/clusters_micro.csv >> $OUTFILE_MICRO
sed -e '1d' /mnt/tmp/dump/NEW/attrExpo_nv_rndseq_tm_Rleft_all_iter/attrExpo_nv_rndseq_tm_Rleft_all_iter_s5/clusters_macro_avg.csv >> $OUTFILE_MACRO_AVG_SPLIT
